server:
    port: 8085 #tomcat port
    servlet:
        context-path: /bootcamp #initial URI path

#database connection (postgres)
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: 123456
    #JPA diretives    
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
        hibernate:
            ddl-auto: none

#self creation project name
application:
    description: SantanderDIO - bootcamp
